#+STARTUP: showall
#+OPTIONS: todo:nil tasks:nil tags:nil toc:nil
#+OPTIONS: d:(not "results")
#+PROPERTY: header-args :eval never-export
#+EXCLUDE_TAGS: noexport
#+LATEX_HEADER: \usepackage{breakurl}
#+LATEX_HEADER: \usepackage{newuli}
#+LATEX_HEADER: \usepackage{uli-german-paragraphs}

\begin{samepage}
* Mindset

This is a coding competition during an assessment center. You free to
form one or more teams. However, the goal of the competition is not to
assess who codes fastest, but which group works best together.

** Rules

   1) A team must have at least 1 member
   2) There is no upper limit to the team size
   3) Each team must accept any person who wishes to be part of the
      team
   4) Once you have joined a team, you cannot change teams (However,
      you can opt to leave the team and work alone)
   5) No one can join a team after 10AM, Nov 27^{th} 2019
   6) The final submission must be an individual submission with code
      and text you wrote yourself.
   7) Teams are free to divide their work as they wish. However:
      A) You cannot share actual code with your team members.
      B) You can share links to code examples found on the web,
         explanations documentation, or ideas.
      C) You can use the TV screens to explain solutions to your team mates
      D) All sharing of links etc must proceed through the ESS345
         Computational Geology discussion board on quercus (Create a
         topic for your group and the post there).

** Advice:

  1) Talk - alot!
  2) Ask
  3) Explain
  4) Create a workplan
  5) Have fun!
 
\end{samepage}
